name: "AWS SQS"
description: "Send message to AWS SQS"
branding:
  icon: "message-square"
  color: "orange"
inputs:
  sqs-url:
    description: "AWS SQS url"
    required: true
  variables:
    description: "variables to send"
    required: true
runs:
  using: "node12"
  main: "dist/index.js"
