name: "AWS SQS"
description: "Send message to AWS SQS"
branding:
  icon: "message-square"
  color: "orange"
inputs:
  sqs-url:
    description: "AWS SQS url"
    required: true
  hasVariables:
    description: "if there are env variables to parsed"
    required: false
  message:
    description: "message boty to send"
    required: true
runs:
  using: "node12"
  main: "index.js"
